[2025-04-29T19:29:48.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T19:29:48.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:29:46.542166+00:00 [queued]>
[2025-04-29T19:29:48.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:29:46.542166+00:00 [queued]>
[2025-04-29T19:29:48.980+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-29T19:29:49.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_pst> on 2025-04-29 19:29:46.542166+00:00
[2025-04-29T19:29:49.014+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T19:29:49.017+0000] {standard_task_runner.py:63} INFO - Started process 1253 to run task
[2025-04-29T19:29:49.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pstspark', 'run_spark_pst', 'manual__2025-04-29T19:29:46.542166+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/pstspark.py', '--cfg-path', '/tmp/tmp61f_dxgv']
[2025-04-29T19:29:49.019+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask run_spark_pst
[2025-04-29T19:29:49.102+0000] {task_command.py:426} INFO - Running <TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:29:46.542166+00:00 [running]> on host 3d59bb7e8591
[2025-04-29T19:29:49.255+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pstspark' AIRFLOW_CTX_TASK_ID='run_spark_pst' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T19:29:46.542166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T19:29:46.542166+00:00'
[2025-04-29T19:29:49.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T19:29:57.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T19:29:57.720+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pstspark.py", line 34, in RunSparkPst
    df = spark.read.jdbc(url=url, table="employees", properties=properties)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 927, in jdbc
    return self._df(self._jreader.jdbc(url, table, jprop))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-3.4.2-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: requirement failed: The driver could not open a JDBC connection. Check the URL: jdbc:postgresql://test
[2025-04-29T19:29:57.788+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pstspark, task_id=run_spark_pst, run_id=manual__2025-04-29T19:29:46.542166+00:00, execution_date=20250429T192946, start_date=20250429T192948, end_date=20250429T192957
[2025-04-29T19:29:57.846+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task run_spark_pst (requirement failed: The driver could not open a JDBC connection. Check the URL: jdbc:postgresql://test; 1253)
[2025-04-29T19:29:57.891+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-29T19:29:57.944+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T19:29:57.953+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
